spring:
  application:
    name: insider-trading-analyzer
  shell:
    interactive:
      enabled: true
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:15432/insider_trading
    username: insider_user
    password: insider_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      # Connection validation
      connection-test-query: SELECT 1
      validation-timeout: 3000
      # Pool sizing
      maximum-pool-size: 10
      minimum-idle: 5
      # Connection lifecycle
      max-lifetime: 1800000  # 30 minutes - prevent stale connections
      idle-timeout: 600000    # 10 minutes - remove idle connections
      connection-timeout: 30000  # 30 seconds - wait time for connection from pool
      # Leak detection (helpful for debugging)
      leak-detection-threshold: 60000  # 1 minute - warn if connection held too long
      # Pool name for logging
      pool-name: InsiderTradingHikariPool
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    schemas: public
  ai:
    ollama:
      chat:
        model: gpt-oss:20b-cloud
        options:
          num-ctx: 16384 # 16k

logging:
  threshold:
    console: ERROR
