name: CI

on:
  push:
    branches: ['**']

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run check
        run: ./gradlew check

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports/tests/**/*
            build/test-results/**/*.xml
          retention-days: 7

      - name: Upload ktlint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-results
          path: build/reports/ktlint/**/*
          retention-days: 7
